fail on exit

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -33,11 +33,14 @@ jobs:
       uses: peter-evans/autopep8@v1
       with:
         args: -d --exit-code --recursive .
-      if: steps.autopep8.outputs.exit-code == 2
+      if: exit-code == 2
       run: exit 1    
       #run: |
         # stop the build if there are Python syntax errors or undefined names
         #flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
+    #- name: Fail on exit autopep8
+      # if: steps.autopep8.outputs.exit-code == 2
+      # run: exit 1    
     - name: Test with pytest
       run: |
         python -m pytest tests
